CI: add cargo-mutants job

diff --git a/.github/workflows/CI-linux.yml b/.github/workflows/CI-linux.yml
--- a/.github/workflows/CI-linux.yml
+++ b/.github/workflows/CI-linux.yml
@@ -206,6 +206,11 @@ jobs:
             curl unzip \
           "
           fi
+          if [ "${{ inputs.job-flavor }}" = "Mutants" ]; then
+          PACKAGES="${PACKAGES} \
+            dasel \
+          "
+          fi
           dpkg-divert --add --rename --divert /usr/bin/cc.original /usr/bin/cc
           dpkg-divert --add --rename --divert /usr/bin/gcc.original /usr/bin/gcc
           dpkg-divert --add --rename --divert /usr/bin/g++.original /usr/bin/g++
@@ -329,6 +334,10 @@ jobs:
           "
           RUST_CRATES="${RUST_CRATES} \
             cargo-nextest \
+          "
+          elif [ "${{ inputs.job-flavor }}" = "Mutants" ]; then
+          RUST_CRATES="${RUST_CRATES} \
+            cargo-mutants \
           "
           elif    [ "${{ inputs.job-flavor }}" = "ASAN" ] \
                || [ "${{ inputs.job-flavor }}" = "MSAN" ] \
@@ -617,6 +626,27 @@ jobs:
           export ${{ inputs.job-flavor }}_OPTIONS="allocator_may_return_null=1"
           cd "${{ env.SRC_DIR }}"
           cargo test --all-targets $BUILD_ARGS --target ${{ env.RUST_TARGET }} --profile ${{ inputs.build-profile }}-sanitized
+      - name: Run tests under cargo-mutants
+        timeout-minutes: 60
+        if: inputs.job-flavor == 'Mutants'
+        run: |
+          set -xe
+          . "$HOME/.cargo/env"
+          cd "${{ env.SRC_DIR }}"
+          FAILURE=0
+          for PKG in $(dasel -r toml -w yaml -f "${{ env.SRC_DIR }}/Cargo.toml" -s 'workspace.members.all()'); do
+            echo "::group::Mutation testing in ${PKG}"
+            set +e
+            cargo mutants -j$(nproc --all) --annotations github --cap-lints true --cargo-arg --target --cargo-arg ${{ env.RUST_TARGET }} --profile ${{ inputs.build-profile }} --dir ${PKG}
+            STATUS=$?
+            set -e
+            if [ $STATUS -ne 0 ]; then
+              echo "::error file=${PKG}/Cargo.toml::mutation testing failed!"
+              FAILURE=1
+            fi
+            echo '::endgroup::'
+          done
+          exit ${FAILURE}
       - name: Dry-run benchmarks
         timeout-minutes: 1
         if: inputs.job-flavor == 'plain'
